add_newline = true

format = """
╭─$directory$git_branch$git_status$python$nodejs$docker_context
╰─$character
"""

[directory]
style = "bold cyan"
truncate_to_repo = false

[git_branch]
symbol = " "

[git_status]
style = "yellow"

[python]
symbol = " "

[nodejs]
symbol = " "

[docker_context]
symbol = " "

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
vimcmd_symbol = "[❮](bold blue)"

[cmd_duration]
disabled = false
min_time = 1000





























